update v2ray version: 4.27.5

diff --git a/v2ray/Dockerfile b/v2ray/Dockerfile
--- a/v2ray/Dockerfile
+++ b/v2ray/Dockerfile
@@ -2,6 +2,7 @@ FROM alpine:latest
 
 ARG V2RAY_VERSION="4.27.5"
 ARG NGINX_VERSION="1.21.1"
+ARG BUILD_CPU_NUM="2"
 
 ENV v2ray_uuid '39c84eb5-6a2b-42d3-ac13-6381a4cca529'
 ENV v2ray_path '68ad'
@@ -21,7 +22,7 @@ RUN apk add --no-cache gcc libc-dev \
     curl gd-dev jq
 
 # Nginx
-RUN wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
+RUN wget -https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
     && wget 'https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1a/openssl-1.1.1a.tar.gz' \
     && tar xzf openssl-1.1.1a.tar.gz \
     && tar zxf nginx-${NGINX_VERSION}.tar.gz && cd nginx-${NGINX_VERSION} \
@@ -31,7 +32,7 @@ RUN wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
        --with-http_v2_module --with-http_ssl_module \
        --with-http_gzip_static_module --with-http_stub_status_module \
        --with-http_sub_module --with-stream --with-stream_ssl_module \
-    && make && make install \
+    && make -j${BUILD_CPU_NUM} && make -j${BUILD_CPU_NUM} install \
     && rm -rf /etc/nginx/html/* \
     && rm -rf /app/openssl-1.1.1a* \
     && rm -rf /var/cache/apk/* \
@@ -40,10 +41,16 @@ RUN wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
 
 # V2ray
 RUN mkdir /app/v2ray && cd $_ \
-    if [ "$(uname -m)" = "x86_64" ]; then export CPU_PLATFORM="64" ; elif [ "$(uname -m)" = "aarch64" ]; then export CPU_PLATFORM="arm64-v8a" ; fi \
-	&& wget --no-check-certificate https://github.com/v2ray/v2ray-core/releases/download/v${V2RAY_VERSION}/v2ray-linux-${CPU_PLATFORM}.zip \
-    && unzip v2ray-linux-${CPU_PLATFORM}.zip \
-    && rm -rf *.{json,sig,dat,systemd} \
+    && if [ "$(uname -m)" = "x86_64" ]; then \
+        export CPU_PLATFORM="64"; \
+    elif [ "$(uname -m)" = "aarch64" ]; then \
+        export CPU_PLATFORM="arm64-v8a"; \
+    else \
+        echo "ERROR: Unsupported architecture: $(uname -m)"; exit 1; \
+    fi \
+	&& wget --no-check-certificate -q https://github.com/v2ray/v2ray-core/releases/download/v${V2RAY_VERSION}/v2ray-linux-${CPU_PLATFORM}.zip \
+    && unzip -q v2ray-linux-${CPU_PLATFORM}.zip \
+    && rm -f *.json *.sig *.dat *.systemd \
     && chmod +x /app/v2ray/* \
     && chmod +x /app/entrypoint.sh
 
